version: "3.7"

networks: 
  frontend:
    name: cookbook_frontend
  backend:
    name: cookbook_backend

services:
  cookbook-database:
    container_name: cookbook-database
    image: postgres:alpine
    environment:
      POSTGRES_DB: cookbook
      POSTGRES_PASSWORD: am!28--zQ
    networks: 
        - backend
    ports:
      - 40000:5432
  cookbook-api:
    container_name: cookbook-api
    build:
      context: ../../
      dockerfile: ./ci/dockerfiles/cookbook-api.Dockerfile
    ports:
      - 9000:9000
    environment:
      - PORT=9000
      - JDBC_DATABASE_URL=jdbc:postgresql://cookbook-database/cookbook?user=postgres&password=am!28--zQ
    networks: 
      - frontend
      - backend
    links: 
      - cookbook-database
    depends_on: 
      - cookbook-database
  cookbook-webapp:
    container_name: cookbook-webapp
    build:
      context: ../../
      dockerfile: ./ci/dockerfiles/cookbook-webapp.Dockerfile
    environment:
      PORT: 80
      BACKEND_URL: http://cookbook-api:9000
    networks: 
      - frontend
    ports:
      - 8080:80
    depends_on: 
      - cookbook-api
