version: "3.7"

networks:
  cookbook-network:

services:
  cookbook-api:
    container_name: cookbook-api
    build:
      context: ../../
      dockerfile: ./ci/dockerfiles/cookbook-api.Dockerfile
    ports:
      - 9000:9000
    environment:
      - PORT=9000
      - JDBC_DATABASE_URL=jdbc:postgresql://cookbook-database:5432/cookbook?user=postgres&password=am!28--zQ
    networks:
      - cookbook-network
  cookbook-webapp:
    container_name: cookbook-webapp
    build:
      context: ../../
      dockerfile: ./ci/dockerfiles/cookbook-webapp.Dockerfile
    environment:
      PORT: 80
      BACKEND_URL: http://cookbook-api:9000
    ports:
      - 8080:80
    networks:
      - cookbook-network    
  cookbook-database:
    container_name: cookbook-database
    image: postgres:alpine
    environment:
      POSTGRES_DB: cookbook
      POSTGRES_PASSWORD: am!28--zQ
    ports:
      - 40000:5432
    networks:
      - cookbook-network
