CREATE TABLE IF NOT EXISTS RecipeTypes (Id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(64) NOT NULL);
ALTER TABLE RecipeTypes ADD CONSTRAINT RecipeTypes_name_UNIQUE UNIQUE (name);

CREATE TABLE IF NOT EXISTS Users (Id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(128) NOT NULL, username VARCHAR(255) NOT NULL, passwordHash VARCHAR(255) NOT NULL);
ALTER TABLE Users ADD CONSTRAINT Users_username_UNIQUE UNIQUE (username);

CREATE TABLE IF NOT EXISTS Recipes (Id INT AUTO_INCREMENT PRIMARY KEY, recipeTypeId INT NOT NULL, userId INT NOT NULL, name VARCHAR(128) NOT NULL,
description VARCHAR(256) NOT NULL, ingredients VARCHAR(2048) NOT NULL, preparingSteps VARCHAR(4096) NOT NULL,
CONSTRAINT FK_Recipes_recipeTypeId_Id FOREIGN KEY (recipeTypeId) REFERENCES RecipeTypes(Id) ON DELETE RESTRICT ON UPDATE RESTRICT,
CONSTRAINT FK_Recipes_userId_Id FOREIGN KEY (userId) REFERENCES Users(Id) ON DELETE RESTRICT ON UPDATE RESTRICT);

CREATE TABLE IF NOT EXISTS Roles (Id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(64) NOT NULL, code VARCHAR(16) NOT NULL, persistent BOOLEAN NOT NULL);
ALTER TABLE Roles ADD CONSTRAINT Roles_code_UNIQUE UNIQUE (code);

CREATE TABLE IF NOT EXISTS UserRoles (Id INT AUTO_INCREMENT PRIMARY KEY, userId INT NOT NULL, roleId INT NOT NULL,
CONSTRAINT FK_UserRoles_userId_Id FOREIGN KEY (userId) REFERENCES Users(Id) ON DELETE RESTRICT ON UPDATE RESTRICT,
CONSTRAINT FK_UserRoles_roleId_Id FOREIGN KEY (roleId) REFERENCES Roles(Id) ON DELETE RESTRICT ON UPDATE RESTRICT);

-- Admin user
INSERT INTO Roles(name, code, persistent) VALUES('User', 'USER', true);
INSERT INTO Roles(name, code, persistent) VALUES('Admin', 'ADMIN', true);
INSERT INTO Users(name, username, passwordHash) VALUES ('Pedro Flores', 'pflores','$2a$10$QSDLTiTQUTLDOzTQPQCfGOuffA3Jphru2DBJOygRLU/PKW.4ruR4S');
INSERT INTO UserRoles (userId, roleId) VALUES(1,1);
INSERT INTO UserRoles (userId, roleId) VALUES(1,2);
