CREATE TABLE IF NOT EXISTS RECIPETYPES (ID INT AUTO_INCREMENT PRIMARY KEY, "NAME" VARCHAR(64) NOT NULL);
ALTER TABLE RECIPETYPES ADD CONSTRAINT RECIPETYPES_NAME_UNIQUE UNIQUE ("NAME");

CREATE TABLE IF NOT EXISTS USERS (ID INT AUTO_INCREMENT PRIMARY KEY, "NAME" VARCHAR(128) NOT NULL, USERNAME VARCHAR(255) NOT NULL, "passwordHash" VARCHAR(255) NOT NULL);
ALTER TABLE USERS ADD CONSTRAINT USERS_USERNAME_UNIQUE UNIQUE (USERNAME);

CREATE TABLE IF NOT EXISTS RECIPES (ID INT AUTO_INCREMENT PRIMARY KEY, "recipeTypeId" INT NOT NULL, "userId" INT NOT NULL, "NAME" VARCHAR(128) NOT NULL, DESCRIPTION VARCHAR(256) NOT NULL, INGREDIENTS VARCHAR(2048) NOT NULL, "preparingSteps" VARCHAR(4096) NOT NULL, CONSTRAINT FK_RECIPES_RECIPETYPEID_ID FOREIGN KEY ("recipeTypeId") REFERENCES RECIPETYPES(ID) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT FK_RECIPES_USERID_ID FOREIGN KEY ("userId") REFERENCES USERS(ID) ON DELETE RESTRICT ON UPDATE RESTRICT);

CREATE TABLE IF NOT EXISTS ROLES (ID INT AUTO_INCREMENT PRIMARY KEY, "NAME" VARCHAR(64) NOT NULL, CODE VARCHAR(16) NOT NULL, PERSISTENT BOOLEAN NOT NULL);
ALTER TABLE ROLES ADD CONSTRAINT ROLES_CODE_UNIQUE UNIQUE (CODE);

CREATE TABLE IF NOT EXISTS USERROLES (ID INT AUTO_INCREMENT PRIMARY KEY, "userId" INT NOT NULL, "roleId" INT NOT NULL, CONSTRAINT FK_USERROLES_USERID_ID FOREIGN KEY ("userId") REFERENCES USERS(ID) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT FK_USERROLES_ROLEID_ID FOREIGN KEY ("roleId") REFERENCES ROLES(ID) ON DELETE RESTRICT ON UPDATE RESTRICT);

INSERT INTO ROLES(NAME, CODE, PERSISTENT) VALUES('User', 'USER', true);
INSERT INTO ROLES(NAME, CODE, PERSISTENT) VALUES('Admin', 'ADMIN', true);