version: '3.7'

services:
  cookbook:
    container_name: cookbook
    build:
      context: ../
      dockerfile: ./dockerfiles/cookbook.Dockerfile
    ports:
      - 9000:9000
    networks:
      - cookbook-network
    environment:
      - COOKBOOK_API_PORT=9000
      - COOKBOOK_DATABASE_JDBCURL=jdbc:mysql://cookbook-database:3306/cookbook
      - COOKBOOK_DATABASE_USERNAME=root
      - COOKBOOK_DATABASE_PASSWORD=am!28--zQ
  cookbook-database:
    container_name: cookbook-database
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: cookbook
      MYSQL_ROOT_PASSWORD: am!28--zQ
    ports:
      - 40000:3306
    networks:
      - cookbook-network
networks:
  cookbook-network:
    name: "cookbook-network"