name: Docker Image CI

on:
  workflow_dispatch:
  release:
    types: [published]

defaults:
  run:
    working-directory: ./

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_PAT }}
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build and push API
      uses: docker/build-push-action@v2
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_PAT }}
        registry: docker.pkg.github.com
        repository: ghcr.io/cookbook-api
        tags: pedrodbflores/cookbook-api:latest 
        context: .
        file: ./ci/dockerfiles/cookbook-api.Dockerfile
        push: true
    - name: Build and Push Webapp
      uses: docker/build-push-action@v2
      with:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_PAT }}
        registry: docker.pkg.github.com
        repository: ghcr.io/cookbook-webapp
        tags: pedrodbflores/cookbook-webapp:latest
        context: .
        file: ./ci/dockerfiles/cookbook-webapp.Dockerfile
        push: true  
