name: Docker Image CI

on:
  workflow_dispatch:
  release:
    types: [published]

defaults:
  run:
    working-directory: ./

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to Heroku registry
      uses: docker/login-action@v1
      with:
        registry: registry.heroku.com
        username: _
        password: ${{ secrets.HEROKU_API_KEY }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build and push API to Heroku
      uses: docker/build-push-action@v2
      with:
        tags: registry.heroku.com/pf-cookbook-api/web
        context: .
        file: ./ci/dockerfiles/cookbook-api.Dockerfile
        push: true
    - name: Build and Push Webapp to Heroku
      uses: docker/build-push-action@v2
      with:
        tags: registry.heroku.com/pf-cookbook-client/web
        context: .
        file: ./ci/dockerfiles/cookbook-webapp.Dockerfile
        push: true 
