name: Docker Image CI

on:
  workflow_dispatch:
  release:
    types: [published]

defaults:
  run:
    working-directory: ./

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Deploy API Image to Heroku App
      uses: jctaveras/heroku-deploy@v2.1.1
      with:
        email: ${{ secrets.HEROKU_EMAIL }} # your heroku email
        api_key: ${{ secrets.HEROKU_API_KEY }} # your  heroku api key
        app_name: ${{ secrets.HEROKU_API_APP_NAME }} # you aplication name
        dockerfile_path: ci/dockerfiles/cookbook-api.Dockerfile
        options: '' # Docker Build Options
        formation: '' # Docker Dyno Formation. By default is web
    - name: Deploy API Image to Heroku App
      uses: jctaveras/heroku-deploy@v2.1.1
      with:
        email: ${{ secrets.HEROKU_EMAIL }} # your heroku email
        api_key: ${{ secrets.HEROKU_API_KEY }} # your  heroku api key
        app_name: ${{ secrets.HEROKU_CLIENT_APP_NAME }} # you aplication name
        dockerfile_path: ci/dockerfiles/cookbook-webapp.Dockerfile
        options: '' # Docker Build Options
        formation: '' # Docker Dyno Formation. By default is web
